### ISSUE TITLE
Getting Cannot find module 'eslint-config-react-app' on npm run all

### ISSUE THREAD

**Issue by gabriel-kohen-jdas** [actions/typescript-action#52]
I've tried running it locally on my Mac and I get:

> eslint src/**/*.ts

Error: Cannot find module 'eslint-config-react-app'
Referenced from: /Users/gabrielkohen/Documents/git/package.json
    at ModuleResolver.resolve (/Users/gabrielkohen/Documents/git/experiments/typescript-action/node_modules/eslint/lib/util/module-resolver.js:72:19)
    at resolve (/Users/gabrielkohen/Documents/git/experiments/typescript-action/node_modules/eslint/lib/config/config-file.js:507:28)
    at load (/Users/gabrielkohen/Documents/git/experiments/typescript-action/node_modules/eslint/lib/config/config-file.js:579:26)
    at /Users/gabrielkohen/Documents/git/experiments/typescript-action/node_modules/eslint/lib/config/config-file.js:453:36
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/gabrielkohen/Documents/git/experiments/typescript-action/node_modules/eslint/lib/config/config-file.js:431:26)
    at loadFromDisk (/Users/gabrielkohen/Documents/git/experiments/typescript-action/node_modules/eslint/lib/config/config-file.js:551:22)
    at Object.load (/Users/gabrielkohen/Documents/git/experiments/typescript-action/node_modules/eslint/lib/config/config-file.js:587:20)
    at Config.getLocalConfigHierarchy (/Users/gabrielkohen/Documents/git/experiments/typescript-action/node_modules/eslint/lib/config.js:240:44)
    at Config.getConfigHierarchy (/Users/gabrielkohen/Documents/git/experiments/typescript-action/node_modules/eslint/lib/config.js:192:43)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! typescript-action@0.0.0 lint: `eslint src/**/*.ts`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the typescript-action@0.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gabrielkohen/.npm/_logs/2020-01-26T17_21_29_686Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! typescript-action@0.0.0 all: `npm run build && npm run format && npm run lint && npm run pack && npm test`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the typescript-action@0.0.0 all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

I made sure I had nothing funny install globally:
:jda-sample-action gabrielkohen$ npm list -g --depth 0
/usr/local/lib
├── n@6.1.3
├── npm@6.12.1
├── npm-install-peers@1.2.1
└── yarn@1.21.1

Ideas?

Thanks.

**Comment by gabriel-kohen-jdas** [comment]
OK. My fault I guess. I happened to have a stray package.json in my home directory. 
Should we add a `"root": true` in the `eslintConfig`?

**Comment by bryanmacfarlane** [comment]
@gabriel-kohen-jdas - thanks for following up
