### ISSUE TITLE
Template not compatible with latest Node.js LTS version (18.14.2)

### ISSUE THREAD

**Issue by f-o-w-l** [actions/typescript-action#646]
With the latest Node version 18.14.2 LTS:

```
$ npm run build && npm run package

> typescript-action@0.0.0 build
> tsc


> typescript-action@0.0.0 package
> ncc build --source-map --license licenses.txt

ncc: Version 0.31.1
ncc: Compiling file index.js into CJS
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at hashOf (/home/fowl/dev/sand/test-ts-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1855992)
    at ncc (/home/fowl/dev/sand/test-ts-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1860457)
    at runCmd (/home/fowl/dev/sand/test-ts-action/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:55128)
    at 819 (/home/fowl/dev/sand/test-ts-action/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:51698)
    at __webpack_require__ (/home/fowl/dev/sand/test-ts-action/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59048)
    at /home/fowl/dev/sand/test-ts-action/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59260
    at /home/fowl/dev/sand/test-ts-action/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59321
    at Object.<anonymous> (/home/fowl/dev/sand/test-ts-action/node_modules/@vercel/ncc/dist/ncc/cli.js:8:28) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

With the older Node.js LTS version 16.13.0, `npm run package` works as expected.

**Comment by ncalteen** [comment]
👋🏻 Hello! Apologies for the delay on this issue. I am going through this repository and making some large updates. This will be resolved by #732
