### ISSUE TITLE
Cannot remove "main" from package.json in favor of "exports"

### ISSUE THREAD

**Issue by dancaugherty** [actions/typescript-action#737]
Hi: i'm relatively new to Actions, but my attempts to migrate from the use of the _main_ key in favor of _exports_ in package.json has been frustrating. 

Within the package.json file of my new repo (which I'll call **foo**), I'd like to switch this:

```
{
   "name" : "foo",
   "main" : "lib/main.js",
   ...
}
```

to this:

```
{
   "name" : "foo",
   "exports" : {
       "." : "./lib/main.js"
   },
   ...
}
```

But I get the following error whenever I run the action:

```
> ncc build --source-map --license licenses.txt

Error: Cannot find module '/home/lanayru/actions-runner/_work/foo/foo'
Require stack:
- /home/lanayru/actions-runner/_work/foo/foo/node_modules/@vercel/ncc/dist/ncc/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at resolve (node:internal/modules/helpers:136:19)
    at runCmd (/home/lanayru/actions-runner/_work/foo/foo/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:81224)
    at 819 (/home/lanayru/actions-runner/_work/foo/foo/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:77787)
    at __webpack_require__ (/home/lanayru/actions-runner/_work/foo/foo/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:88176)
    at /home/lanayru/actions-runner/_work/foo/foo/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:88388
    at /home/lanayru/actions-runner/_work/foo/foo/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:88449
    at Object.<anonymous> (/home/lanayru/actions-runner/_work/foo/foo/node_modules/@vercel/ncc/dist/ncc/cli.js:8:28)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/lanayru/actions-runner/_work/foo/foo/node_modules/@vercel/ncc/dist/ncc/cli.js'
  ]
}
```
So what do I need to do to get my module found?
And could we update the template with this info as well?

**Comment by dancaugherty** [comment]
No luck: "npm run all" still trips on the test step:

```
Error: Cannot find module '/Users/caughert/Documents/dev/foo'
Require stack:
- /Users/caughert/Documents/dev/foo/node_modules/@vercel/ncc/dist/ncc/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at resolve (node:internal/modules/helpers:136:19)
    at runCmd (/Users/caughert/Documents/dev/foo/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:81224)
    at 819 (/Users/caughert/Documents/dev/foo/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:77787)
    at __webpack_require__ (/Users/caughert/Documents/dev/foo/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:88176)
    at /Users/caughert/Documents/dev/foo/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:88388
    at /Users/caughert/Documents/dev/foo/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:88449
    at Object.<anonymous> (/Users/caughert/Documents/dev/foo/node_modules/@vercel/ncc/dist/ncc/cli.js:8:28)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/caughert/Documents/dev/foo/node_modules/@vercel/ncc/dist/ncc/cli.js'
  ]
```

**Comment by ncalteen** [comment]
Sorry this closed automatically when I merged in the other PR. I will take a look at the error output you provided!

**Comment by ncalteen** [comment]
Have you made other changes to `package.json`? If so, could you copy your version in here? Please make sure to remove any sensitive/personal data!

**Comment by dancaugherty** [comment]
Sorry for not replying sooner. Here's my purged package.json file:
```
{
  "name": "foo",
  "version": "0.0.0",
  "private": true,
  "description": "My amazing project",
  "main": "lib/main.js",
  "scripts": {
    "build": "tsc",
    "format": "prettier --write '**/*.ts'",
    "format-check": "prettier --check '**/*.ts'",
    "lint": "eslint src/**/*.ts",
    "package": "ncc build --source-map --license licenses.txt",
    "test": "jest",
    "all": "npm run build && npm run format && npm run lint && npm run package && npm run test"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.example.com/hitcs/foo.git"
  },
  "keywords": [
    "actions",
    "node",
    "setup"
  ],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@actions/core": "^1.10.0",
    "@actions/github": "^5.1.1",
    "check-dependencies": "^1.1.0",
    "http-proxy-agent": "^7.0.0",
    "https-proxy-agent": "^7.0.1",
    "node-fetch": "^2.7.0"
  },
  "devDependencies": {
    "@types/jest": "^29.5.4",
    "@types/jquery": "^3.5.17",
    "@types/node": "^20.5.4",
    "@types/node-fetch": "^2.6.4",
    "@typescript-eslint/parser": "^5.59.2",
    "@vercel/ncc": "^0.36.1",
    "eslint": "^8.39.0",
    "eslint-plugin-github": "^4.9.2",
    "eslint-plugin-jest": "^27.2.1",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.6.4",
    "js-yaml": "^4.1.0",
    "prettier": "^3.0.0",
    "ts-jest": "^29.1.0",
    "typescript": "^5.2.2"
  }
}```

**Comment by ncalteen** [comment]
Thank you! Can you try updating to use the following? (You may need to change `index.ts` and `index.js` to `main.ts` and `main.js`, respectively)

```json
{
  "exports": {
    ".": "./dist/index.js"
  },
  "engines": {
    "node": ">=16"
  },
  "scripts": {
    "bundle": "npm run format && npm run package",
    "format": "prettier --write '**/*.ts'",
    "format-check": "prettier --check '**/*.ts'",
    "lint": "eslint src/**/*.ts",
    "package": "ncc build src/index.ts --license licenses.txt",
    "test": "jest",
    "all": "npm run format && npm run lint && npm run test && npm run package"
  }
}
```

The main differences I see initially are:

- This package doesn't use [`tsc`](https://www.npmjs.com/package/typescript). Instead it opts for [`ncc`](https://www.npmjs.com/package/@vercel/ncc) since that supports bundling all the needed dependencies. More information can be found in the [GitHub docs](https://www.npmjs.com/package/@vercel/ncc).
- By default, `ncc` outputs to `dist/`. I see in your `package.json` that your entrypoint is `lib/main.js`.

Let me know if that works out for you!

**Comment by ncalteen** [comment]
Hey @dancaugherty, just checking in if you had a chance to try the above example. If you are still running into issues let me know!
